apiVersion: apps/v1
kind: Deployment
metadata:
    name: playground-db
    labels:
        app: playground-db
spec:
    selector:
        matchLabels:
            app: playground-db
    replicas: 1
    template:
        metadata:
            labels:
                app: playground-db
        spec:
            containers:
            - name: master
              image: jerre/playground-db:v1.0.0
              ports:
              - containerPort: 5432
              env:
              - name: POSTGRES_PASSWORD
                value: password
